### ISSUE TITLE
lazygit config

### ISSUE THREAD

**Issue by adrien-barret** [Haize-uwu/lazygit-ephemeral#1]
Hi, 

thanks for the port ! I was wondering if you plan to add also the colors to the lazygit plugin ?

**Comment by Haize-uwu** [comment]
Hi

I do not use lazygit much so I haven't considered adding the colors to a lazygit plugin, but I don't mind doing so. Thanks for the suggestion

**Comment by Haize-uwu** [comment]
feel free to test it out 

[here](https://github.com/Haize-uwu/lazygit-ephemeral/)

**Comment by adrien-barret** [comment]
it work for lazygit directly not in lazyvim. I tried `vim.g.lazygit_config = false` but still the promblem. 
But thanks, it's a great place to start !! :)

**Comment by Haize-uwu** [comment]
I am transferring this issue the the lazygit-ephemeral repo.

**Comment by Haize-uwu** [comment]
Appreciate the feedback.
 I have found that by pasting the theme directly in the lazygit `config.yml` and then placing this in your `init.lua` `vim.g.lazygit_config = false` will load lazygit with the theme correctly.
 
 I am not familiar with loading the theme as a plugin in lazyvim, if you have used other lazygit themes in this way I'd like to use those as reference to load this theme correctly.

**Comment by adrien-barret** [comment]
usually, it's already on the neovim theme tbh but it probably take time to do it, I'll take a look later to merge that. I tried `vim.g.lazygit_config = false` into the config folder and weird thing but was not working. but putting it in init.lua as you said work perfectly !

**Comment by Haize-uwu** [comment]
Glad to hear!
Perhaps then the theme can be set directly in the neovim theme that allows it to load as one. I will look into this for the future.

Thanks for your help

**Comment by adrien-barret** [comment]
will follow the updates and let you know if I find something, thanks again for your work !
